#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  set -x

  ps axuf

  case "${DISTRIB_ID}" in
    Alpine)
      ${NOSUDO} sudo apk add openssh
      ;;
    *)
      pkg ensure security/openssh
      ;;
  esac
}

main "$@"
