#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$(type -P ssh)" != "$PKG_HOME/install/bin/ssh" ]]; then
    return 1
  fi

  if touch "$PKG_HOME/install/var/chroot/sshd/.non-root"; then
    sudo install -d "$PKG_HOME/install/var/chroot/sshd" -o root -m 0755
  fi

  return 0
}

main "$@"
