#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Linux)
      if ! type -P ssh >/dev/null; then
        return 1
      fi
      ;;
    *)
      if [[ "$(type -P ssh)" != "$PKG_HOME/install/bin/ssh" ]]; then
        return 1
      fi
      ;;
  esac

  return 0
}

main "$@"
