#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$(type -P ssh)" != "$PKG_HOME/install/bin/ssh" ]]; then
    return 1
  fi

  return 0
}

main "$@"
