#!/usr/bin/env bash

function sshd_server {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default)
      if touch "$PKG_HOME/install/var/chroot/sshd/.non-root"; then
        sudo install -d "$PKG_HOME/install/var/chroot/sshd" -o root -m 0755
      fi
      (set +f; chmod 600 $shome/config/ssh/*key)
      exec $(which "$PKG_HOME/install/sbin/sshd" /usr/sbin/sshd | head -1) -f "$shome/config/ssh/sshd_config" -De
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

sshd_server "$@"
